# Generated by Django 2.0.5 on 2018-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email_responsable', models.EmailField(max_length=70, unique=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
    ]
