# Generated by Django 2.0.5 on 2018-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermandad',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hermandad',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
